issuer:
  name: Foo Bar
  url: http://badges.bar.org
  email: foo@bar.org
urlmap:
  assertion: /assertions/:recipient/:badge.json
  evidence: /assertions/:recipient/:badge.html
  badge: /badges/:badge.json
  criteria: /badges/:badge.html
  image: /badges/:badge.png
recipients:
  # Add badge recipients here.
  pat: Pat Person <pat@person.com>
